export interface SelfTunerQuestion {
  id: string;
  topic: string;
  type: 'SPECIFIC' | 'GENERIC' | 'PROCEDURAL';
  question: string;
  citation: string;
}

export const SELF_TUNER_QUESTIONS: SelfTunerQuestion[] = [
  // Safety Officer (Rule 1030) - 10 questions
  {
    id: 'SO-001',
    topic: 'Safety Officer',
    type: 'SPECIFIC',
    question: 'How many training hours are required for SO1 certification?',
    citation: 'Rule 1030',
  },
  {
    id: 'SO-002',
    topic: 'Safety Officer',
    type: 'SPECIFIC',
    question: 'How many training hours are required for SO2 certification?',
    citation: 'Rule 1030',
  },
  {
    id: 'SO-003',
    topic: 'Safety Officer',
    type: 'SPECIFIC',
    question: 'How many training hours are required for SO3 or COSH certification?',
    citation: 'Rule 1030',
  },
  {
    id: 'SO-004',
    topic: 'Safety Officer',
    type: 'SPECIFIC',
    question: 'What is the renewal requirement for SO3/COSH?',
    citation: 'Rule 1030',
  },
  {
    id: 'SO-005',
    topic: 'Safety Officer',
    type: 'SPECIFIC',
    question: 'What is the renewal requirement for SO2?',
    citation: 'Rule 1030',
  },
  {
    id: 'SO-006',
    topic: 'Safety Officer',
    type: 'SPECIFIC',
    question: 'What safety officer is required for construction projects?',
    citation: 'Rule 1030',
  },
  {
    id: 'SO-007',
    topic: 'Safety Officer',
    type: 'GENERIC',
    question: 'What are the different safety officer levels in the Philippines?',
    citation: 'Rule 1030',
  },
  {
    id: 'SO-008',
    topic: 'Safety Officer',
    type: 'SPECIFIC',
    question: 'What safety officer is required for a high-risk workplace with 150 workers?',
    citation: 'Rule 1030',
  },
  {
    id: 'SO-009',
    topic: 'Safety Officer',
    type: 'PROCEDURAL',
    question: 'How does a safety officer maintain their certification?',
    citation: 'Rule 1030',
  },
  {
    id: 'SO-010',
    topic: 'Safety Officer',
    type: 'SPECIFIC',
    question: 'What is the minimum education requirement for SO3/COSH?',
    citation: 'Rule 1030',
  },

  // HSC (Rule 1040) - 10 questions
  {
    id: 'HSC-001',
    topic: 'HSC',
    type: 'SPECIFIC',
    question: 'When is a Health and Safety Committee required?',
    citation: 'Rule 1040',
  },
  {
    id: 'HSC-002',
    topic: 'HSC',
    type: 'SPECIFIC',
    question: 'How often should HSC meetings be held in hazardous workplaces?',
    citation: 'Rule 1040',
  },
  {
    id: 'HSC-003',
    topic: 'HSC',
    type: 'SPECIFIC',
    question: 'How often should HSC meetings be held in non-hazardous workplaces?',
    citation: 'Rule 1040',
  },
  {
    id: 'HSC-004',
    topic: 'HSC',
    type: 'SPECIFIC',
    question: 'What is the term of office for Type A HSC worker members?',
    citation: 'Rule 1040',
  },
  {
    id: 'HSC-005',
    topic: 'HSC',
    type: 'SPECIFIC',
    question: 'What type of HSC is required for a workplace with 500 workers?',
    citation: 'Rule 1040',
  },
  {
    id: 'HSC-006',
    topic: 'HSC',
    type: 'GENERIC',
    question: 'What are the duties of a Health and Safety Committee?',
    citation: 'Rule 1040',
  },
  {
    id: 'HSC-007',
    topic: 'HSC',
    type: 'PROCEDURAL',
    question: 'How to organize a Health and Safety Committee?',
    citation: 'Rule 1040',
  },
  {
    id: 'HSC-008',
    topic: 'HSC',
    type: 'SPECIFIC',
    question: 'What are the types of Health and Safety Committee?',
    citation: 'Rule 1040',
  },
  {
    id: 'HSC-009',
    topic: 'HSC',
    type: 'SPECIFIC',
    question: 'Who serves as secretary of a Type A or Type B HSC?',
    citation: 'Rule 1040',
  },
  {
    id: 'HSC-010',
    topic: 'HSC',
    type: 'SPECIFIC',
    question: 'What is the composition of a Type C HSC?',
    citation: 'Rule 1040',
  },

  // Penalties (RA 11058) - 10 questions
  {
    id: 'PEN-001',
    topic: 'Penalties',
    type: 'SPECIFIC',
    question: 'What is the penalty for first offense OSH violation for a small enterprise?',
    citation: 'RA 11058',
  },
  {
    id: 'PEN-002',
    topic: 'Penalties',
    type: 'SPECIFIC',
    question: 'What is the penalty for first offense OSH violation for a micro enterprise?',
    citation: 'RA 11058',
  },
  {
    id: 'PEN-003',
    topic: 'Penalties',
    type: 'SPECIFIC',
    question: 'What is the penalty for first offense for a large enterprise?',
    citation: 'RA 11058',
  },
  {
    id: 'PEN-004',
    topic: 'Penalties',
    type: 'SPECIFIC',
    question: 'What is the penalty for death due to OSH violation?',
    citation: 'RA 11058',
  },
  {
    id: 'PEN-005',
    topic: 'Penalties',
    type: 'SPECIFIC',
    question: 'What is the penalty for willful OSH violation?',
    citation: 'RA 11058',
  },
  {
    id: 'PEN-006',
    topic: 'Penalties',
    type: 'SPECIFIC',
    question: 'Who is liable for OSH violations involving contractors?',
    citation: 'RA 11058',
  },
  {
    id: 'PEN-007',
    topic: 'Penalties',
    type: 'GENERIC',
    question: 'What are the penalties under RA 11058?',
    citation: 'RA 11058',
  },
  {
    id: 'PEN-008',
    topic: 'Penalties',
    type: 'SPECIFIC',
    question: 'What is the third offense penalty for a medium enterprise?',
    citation: 'RA 11058',
  },
  {
    id: 'PEN-009',
    topic: 'Penalties',
    type: 'GENERIC',
    question: 'Can DOLE stop work operations due to OSH violations?',
    citation: 'RA 11058',
  },
  {
    id: 'PEN-010',
    topic: 'Penalties',
    type: 'SPECIFIC',
    question: 'What is the second offense penalty for a small enterprise?',
    citation: 'RA 11058',
  },

  // Environmental Controls (Rule 1070) - 10 questions
  {
    id: 'ENV-001',
    topic: 'Environmental',
    type: 'SPECIFIC',
    question: 'What is the permissible noise exposure for 8 hours?',
    citation: 'Rule 1070',
  },
  {
    id: 'ENV-002',
    topic: 'Environmental',
    type: 'SPECIFIC',
    question: 'What is the permissible noise exposure for 4 hours?',
    citation: 'Rule 1070',
  },
  {
    id: 'ENV-003',
    topic: 'Environmental',
    type: 'SPECIFIC',
    question: 'What is the peak impact noise ceiling?',
    citation: 'Rule 1070',
  },
  {
    id: 'ENV-004',
    topic: 'Environmental',
    type: 'SPECIFIC',
    question: 'What is the required illumination for general work areas?',
    citation: 'Rule 1070',
  },
  {
    id: 'ENV-005',
    topic: 'Environmental',
    type: 'SPECIFIC',
    question: 'What is the required illumination for passageways?',
    citation: 'Rule 1070',
  },
  {
    id: 'ENV-006',
    topic: 'Environmental',
    type: 'SPECIFIC',
    question: 'What is the air supply requirement per worker?',
    citation: 'Rule 1070',
  },
  {
    id: 'ENV-007',
    topic: 'Environmental',
    type: 'GENERIC',
    question: 'What are the illumination requirements under OSHS?',
    citation: 'Rule 1070',
  },
  {
    id: 'ENV-008',
    topic: 'Environmental',
    type: 'SPECIFIC',
    question: 'What is the minimum emergency lighting requirement?',
    citation: 'Rule 1070',
  },
  {
    id: 'ENV-009',
    topic: 'Environmental',
    type: 'PROCEDURAL',
    question: 'How often should working environment be measured in hazardous workplaces?',
    citation: 'Rule 1070',
  },
  {
    id: 'ENV-010',
    topic: 'Environmental',
    type: 'SPECIFIC',
    question: 'What is the permissible heat stress for continuous work?',
    citation: 'Rule 1070',
  },

  // Registration (Rule 1020) - 8 questions
  {
    id: 'REG-001',
    topic: 'Registration',
    type: 'SPECIFIC',
    question: 'When must an establishment register with DOLE?',
    citation: 'Rule 1020',
  },
  {
    id: 'REG-002',
    topic: 'Registration',
    type: 'SPECIFIC',
    question: 'What is the deadline for OSH registration after business registration?',
    citation: 'Rule 1020',
  },
  {
    id: 'REG-003',
    topic: 'Registration',
    type: 'PROCEDURAL',
    question: 'What documents are required for DOLE registration?',
    citation: 'Rule 1020',
  },
  {
    id: 'REG-004',
    topic: 'Registration',
    type: 'SPECIFIC',
    question: 'What is the form number for establishment registration?',
    citation: 'Rule 1020',
  },
  {
    id: 'REG-005',
    topic: 'Registration',
    type: 'PROCEDURAL',
    question: 'How to register an establishment with DOLE?',
    citation: 'Rule 1020',
  },
  {
    id: 'REG-006',
    topic: 'Registration',
    type: 'SPECIFIC',
    question: 'What changes require updating DOLE registration?',
    citation: 'Rule 1020',
  },
  {
    id: 'REG-007',
    topic: 'Registration',
    type: 'SPECIFIC',
    question: 'Is there a fee for DOLE establishment registration?',
    citation: 'Rule 1020',
  },
  {
    id: 'REG-008',
    topic: 'Registration',
    type: 'GENERIC',
    question: 'What are the requirements for DOLE establishment registration?',
    citation: 'Rule 1020',
  },

  // PPE (Rule 1080) - 8 questions
  {
    id: 'PPE-001',
    topic: 'PPE',
    type: 'SPECIFIC',
    question: 'Who is responsible for providing PPE to workers?',
    citation: 'Rule 1080',
  },
  {
    id: 'PPE-002',
    topic: 'PPE',
    type: 'SPECIFIC',
    question: 'Can employers charge workers for PPE?',
    citation: 'Rule 1080',
  },
  {
    id: 'PPE-003',
    topic: 'PPE',
    type: 'GENERIC',
    question: 'What are the types of PPE required under OSHS?',
    citation: 'Rule 1080',
  },
  {
    id: 'PPE-004',
    topic: 'PPE',
    type: 'SPECIFIC',
    question: 'When is hearing protection required?',
    citation: 'Rule 1080',
  },
  {
    id: 'PPE-005',
    topic: 'PPE',
    type: 'SPECIFIC',
    question: 'What fall protection is required for work above 1.8 meters?',
    citation: 'Rule 1080',
  },
  {
    id: 'PPE-006',
    topic: 'PPE',
    type: 'PROCEDURAL',
    question: 'How should PPE be maintained and stored?',
    citation: 'Rule 1080',
  },
  {
    id: 'PPE-007',
    topic: 'PPE',
    type: 'SPECIFIC',
    question: 'What are the requirements for safety helmets?',
    citation: 'Rule 1080',
  },
  {
    id: 'PPE-008',
    topic: 'PPE',
    type: 'SPECIFIC',
    question: 'What eye protection is required for welding?',
    citation: 'Rule 1080',
  },

  // Accident Reporting (Rule 1050) - 6 questions
  {
    id: 'ACC-001',
    topic: 'Accident Reporting',
    type: 'SPECIFIC',
    question: 'What is the deadline for reporting fatal accidents to DOLE?',
    citation: 'Rule 1050',
  },
  {
    id: 'ACC-002',
    topic: 'Accident Reporting',
    type: 'SPECIFIC',
    question: 'What is the form number for Work Accident/Illness Report?',
    citation: 'Rule 1050',
  },
  {
    id: 'ACC-003',
    topic: 'Accident Reporting',
    type: 'GENERIC',
    question: 'What types of accidents must be reported to DOLE?',
    citation: 'Rule 1050',
  },
  {
    id: 'ACC-004',
    topic: 'Accident Reporting',
    type: 'SPECIFIC',
    question: 'How is the frequency rate calculated?',
    citation: 'Rule 1050',
  },
  {
    id: 'ACC-005',
    topic: 'Accident Reporting',
    type: 'SPECIFIC',
    question: 'How is the severity rate calculated?',
    citation: 'Rule 1050',
  },
  {
    id: 'ACC-006',
    topic: 'Accident Reporting',
    type: 'PROCEDURAL',
    question: 'What is the procedure for accident investigation?',
    citation: 'Rule 1050',
  },

  // Premises (Rule 1060) - 6 questions
  {
    id: 'PRM-001',
    topic: 'Premises',
    type: 'SPECIFIC',
    question: 'What is the minimum headroom for workplaces?',
    citation: 'Rule 1060',
  },
  {
    id: 'PRM-002',
    topic: 'Premises',
    type: 'SPECIFIC',
    question: 'What is the minimum floor space per worker?',
    citation: 'Rule 1060',
  },
  {
    id: 'PRM-003',
    topic: 'Premises',
    type: 'SPECIFIC',
    question: 'What is the minimum width for stairways?',
    citation: 'Rule 1060',
  },
  {
    id: 'PRM-004',
    topic: 'Premises',
    type: 'SPECIFIC',
    question: 'What is the required height for guardrails?',
    citation: 'Rule 1060',
  },
  {
    id: 'PRM-005',
    topic: 'Premises',
    type: 'GENERIC',
    question: 'What are the housekeeping requirements under OSHS?',
    citation: 'Rule 1060',
  },
  {
    id: 'PRM-006',
    topic: 'Premises',
    type: 'SPECIFIC',
    question: 'What are the emergency exit requirements?',
    citation: 'Rule 1060',
  },

  // Confined Spaces (Rule 1120) - 4 questions
  {
    id: 'CNF-001',
    topic: 'Confined Space',
    type: 'SPECIFIC',
    question: 'What is required before entering a confined space?',
    citation: 'Rule 1120',
  },
  {
    id: 'CNF-002',
    topic: 'Confined Space',
    type: 'SPECIFIC',
    question: 'What is the minimum oxygen level for confined space entry?',
    citation: 'Rule 1120',
  },
  {
    id: 'CNF-003',
    topic: 'Confined Space',
    type: 'PROCEDURAL',
    question: 'What is the role of an entry watcher in confined space operations?',
    citation: 'Rule 1120',
  },
  {
    id: 'CNF-004',
    topic: 'Confined Space',
    type: 'GENERIC',
    question: 'What are the confined space entry requirements under OSHS?',
    citation: 'Rule 1120',
  },

  // Health Services (Rule 1960) - 4 questions
  {
    id: 'HLT-001',
    topic: 'Health Services',
    type: 'SPECIFIC',
    question: 'When is a workplace clinic required?',
    citation: 'Rule 1960',
  },
  {
    id: 'HLT-002',
    topic: 'Health Services',
    type: 'SPECIFIC',
    question: 'How many first aiders are required per shift?',
    citation: 'Rule 1960',
  },
  {
    id: 'HLT-003',
    topic: 'Health Services',
    type: 'SPECIFIC',
    question: 'What medical examinations are required for workers?',
    citation: 'Rule 1960',
  },
  {
    id: 'HLT-004',
    topic: 'Health Services',
    type: 'GENERIC',
    question: 'What are the occupational health service requirements under OSHS?',
    citation: 'Rule 1960',
  },

  // Hazardous Materials (Rule 1090) - 4 questions
  {
    id: 'HAZ-001',
    topic: 'Hazardous Materials',
    type: 'SPECIFIC',
    question: 'What labeling is required for hazardous chemicals?',
    citation: 'Rule 1090',
  },
  {
    id: 'HAZ-002',
    topic: 'Hazardous Materials',
    type: 'SPECIFIC',
    question: 'What is an SDS or MSDS?',
    citation: 'Rule 1090',
  },
  {
    id: 'HAZ-003',
    topic: 'Hazardous Materials',
    type: 'PROCEDURAL',
    question: 'How should hazardous chemicals be stored?',
    citation: 'Rule 1090',
  },
  {
    id: 'HAZ-004',
    topic: 'Hazardous Materials',
    type: 'GENERIC',
    question: 'What are the requirements for handling hazardous materials?',
    citation: 'Rule 1090',
  },
];
