// OSH Study Mode - Flashcards and Quiz Questions Data
// Organized by topic for Philippine OSH interview preparation

export interface Flashcard {
  id: string;
  topic: string;
  question: string;
  answer: string;
  citation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface QuizQuestion {
  id: string;
  topic: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  citation: string;
}

export type StudyTopic =
  | 'safety-officers'
  | 'committee'
  | 'reporting'
  | 'worker-rights'
  | 'penalties'
  | 'environmental'
  | 'premises'
  | 'ppe'
  | 'registration'
  | 'confined-spaces'
  | 'hazardous'
  | 'health-services';

export const TOPIC_INFO: Record<StudyTopic, { name: string; icon: string; priority: 'high' | 'medium' | 'low' }> = {
  'safety-officers': { name: 'Safety Officers', icon: '👷', priority: 'high' },
  'committee': { name: 'Health & Safety Committee', icon: '👥', priority: 'high' },
  'reporting': { name: 'Accident Reporting', icon: '📋', priority: 'high' },
  'worker-rights': { name: 'Worker Rights', icon: '✊', priority: 'high' },
  'penalties': { name: 'Penalties', icon: '⚖️', priority: 'high' },
  'environmental': { name: 'Environmental Standards', icon: '🌡️', priority: 'medium' },
  'premises': { name: 'Premises Requirements', icon: '🏢', priority: 'medium' },
  'ppe': { name: 'PPE Requirements', icon: '🦺', priority: 'medium' },
  'registration': { name: 'Registration', icon: '📝', priority: 'medium' },
  'confined-spaces': { name: 'Confined Spaces', icon: '🚧', priority: 'low' },
  'hazardous': { name: 'Hazardous Materials', icon: '☢️', priority: 'low' },
  'health-services': { name: 'Health Services', icon: '🏥', priority: 'low' },
};

// ============================================
// FLASHCARDS - 150+ cards organized by topic
// ============================================

export const FLASHCARDS: Flashcard[] = [
  // ===========================================
  // SAFETY OFFICERS (20 cards)
  // ===========================================
  {
    id: 'so-1',
    topic: 'safety-officers',
    question: 'What are the SO1 training hours?',
    answer: '8 hours (Basic Occupational Safety and Health for Workers)',
    citation: 'Rule 1030, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'so-2',
    topic: 'safety-officers',
    question: 'What are the SO2 training hours?',
    answer: '40 hours (Basic Occupational Safety and Health - BOSH)',
    citation: 'Rule 1030, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'so-3',
    topic: 'safety-officers',
    question: 'What are the SO3 training hours?',
    answer: '80 hours (40 hours BOSH + 40 hours Construction Safety)',
    citation: 'Rule 1030, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'so-4',
    topic: 'safety-officers',
    question: 'What are the SO4 training hours?',
    answer: '120 hours (40 BOSH + 40 COSH + 40 specialized modules)',
    citation: 'Rule 1030, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'so-5',
    topic: 'safety-officers',
    question: 'How often is refresher training required for Safety Officers?',
    answer: 'Every 2 years',
    citation: 'Rule 1030.4, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'so-6',
    topic: 'safety-officers',
    question: 'Non-hazardous workplace with 51-200 workers requires which SO level?',
    answer: 'Part-time SO2',
    citation: 'Rule 1033, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'so-7',
    topic: 'safety-officers',
    question: 'Hazardous workplace with 1-9 workers requires which SO level?',
    answer: 'Part-time SO1',
    citation: 'Rule 1033, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'so-8',
    topic: 'safety-officers',
    question: 'Highly hazardous workplace with 201+ workers requires which SO level?',
    answer: 'Full-time SO4 + 1 additional SO for every 250 excess workers',
    citation: 'Rule 1033, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'so-9',
    topic: 'safety-officers',
    question: 'What is BOSH training?',
    answer: 'Basic Occupational Safety and Health - 40-hour mandatory training for SO2',
    citation: 'Rule 1030, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'so-10',
    topic: 'safety-officers',
    question: 'What is COSH training?',
    answer: 'Construction Occupational Safety and Health - 40-hour training for construction sites',
    citation: 'D.O. 13, Series of 1998',
    difficulty: 'easy',
  },
  {
    id: 'so-11',
    topic: 'safety-officers',
    question: 'Non-hazardous workplace with 201+ workers requires which SO level?',
    answer: 'Full-time SO2 + 1 additional for every 400 excess workers',
    citation: 'Rule 1033, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'so-12',
    topic: 'safety-officers',
    question: 'Hazardous workplace with 10-50 workers requires which SO level?',
    answer: 'Part-time SO2',
    citation: 'Rule 1033, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'so-13',
    topic: 'safety-officers',
    question: 'Highly hazardous workplace with 10-50 workers requires which SO level?',
    answer: 'Full-time SO2',
    citation: 'Rule 1033, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'so-14',
    topic: 'safety-officers',
    question: 'What are the main duties of a Safety Officer?',
    answer: 'Conduct safety inspections, investigate accidents, prepare reports, maintain safety records, train workers, enforce OSH policies',
    citation: 'Rule 1030, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'so-15',
    topic: 'safety-officers',
    question: 'Non-hazardous 1-9 workers - SO requirement?',
    answer: 'Part-time SO1 or employer serves as SO',
    citation: 'Rule 1033, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'so-16',
    topic: 'safety-officers',
    question: 'Can an employer act as the Safety Officer?',
    answer: 'Yes, in non-hazardous workplaces with 1-9 workers, if they have SO1 training',
    citation: 'Rule 1033, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'so-17',
    topic: 'safety-officers',
    question: 'Hazardous workplace with 51-200 workers requires which SO level?',
    answer: 'Full-time SO2',
    citation: 'Rule 1033, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'so-18',
    topic: 'safety-officers',
    question: 'What is the minimum SO requirement for a construction project?',
    answer: 'At least one SO3 for construction sites regardless of worker count',
    citation: 'D.O. 13, s. 1998',
    difficulty: 'medium',
  },
  {
    id: 'so-19',
    topic: 'safety-officers',
    question: 'How long is the PCSO (Post-Certification Safety Officer) training?',
    answer: '16 hours refresher training',
    citation: 'Rule 1030.4, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'so-20',
    topic: 'safety-officers',
    question: 'Who accredits Safety Officers in the Philippines?',
    answer: 'Bureau of Working Conditions (BWC) under DOLE',
    citation: 'Rule 1030, OSHS',
    difficulty: 'easy',
  },

  // ===========================================
  // HEALTH & SAFETY COMMITTEE (20 cards)
  // ===========================================
  {
    id: 'hsc-1',
    topic: 'committee',
    question: 'What are the 5 types of Health and Safety Committees?',
    answer: 'Type A, B, C, D, and E (based on workplace size and hazard level)',
    citation: 'Rule 1040, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hsc-2',
    topic: 'committee',
    question: 'How often must the Health and Safety Committee meet?',
    answer: 'At least once a month',
    citation: 'Rule 1040.6, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hsc-3',
    topic: 'committee',
    question: 'When must committees be reorganized?',
    answer: 'Every January',
    citation: 'Rule 1040.5, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-4',
    topic: 'committee',
    question: 'Type A Committee composition?',
    answer: '2 members: 1 management, 1 worker representative',
    citation: 'Rule 1040, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-5',
    topic: 'committee',
    question: 'Type B Committee composition?',
    answer: '4 members: 2 management, 2 worker representatives',
    citation: 'Rule 1040, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-6',
    topic: 'committee',
    question: 'Type C Committee composition?',
    answer: '6 members: 3 management, 3 worker representatives',
    citation: 'Rule 1040, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-7',
    topic: 'committee',
    question: 'Type D Committee composition?',
    answer: '8 members: 4 management, 4 worker representatives',
    citation: 'Rule 1040, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-8',
    topic: 'committee',
    question: 'Type E Committee composition?',
    answer: '12 members: 6 management, 6 worker representatives',
    citation: 'Rule 1040, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-9',
    topic: 'committee',
    question: 'Non-hazardous 1-9 workers - which HSC type?',
    answer: 'No committee required (employer/manager handles OSH)',
    citation: 'Rule 1040, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hsc-10',
    topic: 'committee',
    question: 'Non-hazardous 10-50 workers - which HSC type?',
    answer: 'Type A (2 members)',
    citation: 'Rule 1040, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-11',
    topic: 'committee',
    question: 'Non-hazardous 51-200 workers - which HSC type?',
    answer: 'Type B (4 members)',
    citation: 'Rule 1040, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-12',
    topic: 'committee',
    question: 'Non-hazardous 201-500 workers - which HSC type?',
    answer: 'Type C (6 members)',
    citation: 'Rule 1040, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-13',
    topic: 'committee',
    question: 'What is the primary function of the HSC?',
    answer: 'Plan, develop, oversee, and evaluate OSH programs; investigate accidents; recommend safety measures',
    citation: 'Rule 1040.6, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hsc-14',
    topic: 'committee',
    question: 'Hazardous 10-50 workers - which HSC type?',
    answer: 'Type B (4 members)',
    citation: 'Rule 1040, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-15',
    topic: 'committee',
    question: 'Hazardous 201-500 workers - which HSC type?',
    answer: 'Type D (8 members)',
    citation: 'Rule 1040, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'hsc-16',
    topic: 'committee',
    question: 'Who chairs the Health and Safety Committee?',
    answer: 'A management representative designated by the employer',
    citation: 'Rule 1040.5, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hsc-17',
    topic: 'committee',
    question: 'Must HSC meeting minutes be recorded?',
    answer: 'Yes, minutes must be recorded and kept for at least 5 years',
    citation: 'Rule 1040.7, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hsc-18',
    topic: 'committee',
    question: 'Non-hazardous 501+ workers - which HSC type?',
    answer: 'Type D (8 members)',
    citation: 'Rule 1040, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'hsc-19',
    topic: 'committee',
    question: 'Hazardous 501+ workers - which HSC type?',
    answer: 'Type E (12 members)',
    citation: 'Rule 1040, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'hsc-20',
    topic: 'committee',
    question: 'How are worker representatives in HSC selected?',
    answer: 'Elected by workers or designated by union (if applicable)',
    citation: 'Rule 1040.5, OSHS',
    difficulty: 'medium',
  },

  // ===========================================
  // ACCIDENT REPORTING (15 cards)
  // ===========================================
  {
    id: 'ar-1',
    topic: 'reporting',
    question: 'Deadline for fatal accident initial report?',
    answer: '24 hours (immediately notify DOLE Regional Office)',
    citation: 'Rule 1050.1, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ar-2',
    topic: 'reporting',
    question: 'When is the monthly WAIR due?',
    answer: '20th of the following month (not 30th)',
    citation: 'Rule 1050, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ar-3',
    topic: 'reporting',
    question: 'When is the annual accident report due?',
    answer: 'January 30 of the following year',
    citation: 'Rule 1050, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ar-4',
    topic: 'reporting',
    question: 'What does WAIR stand for?',
    answer: 'Work Accident/Illness Report',
    citation: 'Rule 1050, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ar-5',
    topic: 'reporting',
    question: 'What form is used for accident reporting?',
    answer: 'DOLE-BWC-HSD-IP-6 (Employers Report of Accident/Illness)',
    citation: 'Rule 1050, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ar-6',
    topic: 'reporting',
    question: 'What should be preserved after a fatal/serious accident?',
    answer: 'The accident scene - do not disturb until investigated by DOLE',
    citation: 'Rule 1050.2, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ar-7',
    topic: 'reporting',
    question: 'How long must accident records be kept?',
    answer: 'At least 5 years',
    citation: 'Rule 1050.4, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ar-8',
    topic: 'reporting',
    question: 'What is a "lost time accident"?',
    answer: 'An accident causing the worker to miss at least one full day of work',
    citation: 'Rule 1050, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ar-9',
    topic: 'reporting',
    question: 'What is a "disabling injury"?',
    answer: 'An injury preventing the worker from performing normal duties for at least one day',
    citation: 'Rule 1050, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ar-10',
    topic: 'reporting',
    question: 'What must be reported within 24 hours besides fatalities?',
    answer: 'Serious injuries requiring hospitalization, and dangerous occurrences',
    citation: 'Rule 1050.1, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ar-11',
    topic: 'reporting',
    question: 'What is a "dangerous occurrence"?',
    answer: 'Events that could have caused injury/death (explosions, structural collapse, fire, chemical spill)',
    citation: 'Rule 1050, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ar-12',
    topic: 'reporting',
    question: 'Who investigates workplace accidents?',
    answer: 'The employer, Safety Officer, HSC, and DOLE (for serious/fatal accidents)',
    citation: 'Rule 1050.3, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ar-13',
    topic: 'reporting',
    question: 'What information goes in an accident report?',
    answer: 'Date/time/place, injured person details, nature of injury, cause, witnesses, corrective actions',
    citation: 'Rule 1050, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ar-14',
    topic: 'reporting',
    question: 'Can employers be penalized for not reporting accidents?',
    answer: 'Yes, failure to report is a violation subject to penalties under RA 11058',
    citation: 'RA 11058, Section 12',
    difficulty: 'hard',
  },
  {
    id: 'ar-15',
    topic: 'reporting',
    question: 'Zero accident month - still need to file WAIR?',
    answer: 'Yes, submit WAIR showing zero accidents (nil report)',
    citation: 'Rule 1050, OSHS',
    difficulty: 'medium',
  },

  // ===========================================
  // WORKER RIGHTS (15 cards)
  // ===========================================
  {
    id: 'wr-1',
    topic: 'worker-rights',
    question: 'What is the right to know?',
    answer: 'Workers must be informed about workplace hazards, risks, and safety measures',
    citation: 'RA 11058, Section 6',
    difficulty: 'easy',
  },
  {
    id: 'wr-2',
    topic: 'worker-rights',
    question: 'What is the right to refuse unsafe work?',
    answer: 'Workers can refuse work they believe poses imminent danger without retaliation',
    citation: 'RA 11058, Section 6',
    difficulty: 'easy',
  },
  {
    id: 'wr-3',
    topic: 'worker-rights',
    question: 'What is the right to report?',
    answer: 'Workers can report safety violations to DOLE without fear of retaliation',
    citation: 'RA 11058, Section 6',
    difficulty: 'easy',
  },
  {
    id: 'wr-4',
    topic: 'worker-rights',
    question: 'Who pays for PPE?',
    answer: 'The employer must provide PPE free of charge to workers',
    citation: 'RA 11058, Section 5; Rule 1080, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'wr-5',
    topic: 'worker-rights',
    question: 'Can workers be charged for safety equipment?',
    answer: 'No, employers cannot charge or deduct for PPE from workers wages',
    citation: 'RA 11058, Section 5',
    difficulty: 'easy',
  },
  {
    id: 'wr-6',
    topic: 'worker-rights',
    question: 'Can a worker be fired for refusing unsafe work?',
    answer: 'No, retaliation for exercising OSH rights is prohibited and punishable',
    citation: 'RA 11058, Section 7',
    difficulty: 'medium',
  },
  {
    id: 'wr-7',
    topic: 'worker-rights',
    question: 'Do workers have a right to participate in OSH programs?',
    answer: 'Yes, workers have the right to participate in HSC and safety activities',
    citation: 'RA 11058, Section 6; Rule 1040, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'wr-8',
    topic: 'worker-rights',
    question: 'What is workers duty regarding PPE?',
    answer: 'Workers must use PPE provided, follow safety rules, and report hazards',
    citation: 'RA 11058, Section 8',
    difficulty: 'medium',
  },
  {
    id: 'wr-9',
    topic: 'worker-rights',
    question: 'Can workers request safety data sheets for chemicals?',
    answer: 'Yes, workers have the right to access SDS/MSDS for chemicals they work with',
    citation: 'Rule 1090, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'wr-10',
    topic: 'worker-rights',
    question: 'Right to free medical examination?',
    answer: 'Workers exposed to hazards have the right to free occupational health exams',
    citation: 'Rule 1960, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'wr-11',
    topic: 'worker-rights',
    question: 'Can workers be required to buy their own safety shoes?',
    answer: 'No, all required PPE including safety shoes must be provided free by employer',
    citation: 'RA 11058, Section 5',
    difficulty: 'easy',
  },
  {
    id: 'wr-12',
    topic: 'worker-rights',
    question: 'Do contractual workers have OSH rights?',
    answer: 'Yes, all workers regardless of employment status have equal OSH rights',
    citation: 'RA 11058, Section 4',
    difficulty: 'medium',
  },
  {
    id: 'wr-13',
    topic: 'worker-rights',
    question: 'What protection exists for OSH whistleblowers?',
    answer: 'Workers reporting violations are protected from dismissal, suspension, or discrimination',
    citation: 'RA 11058, Section 7',
    difficulty: 'medium',
  },
  {
    id: 'wr-14',
    topic: 'worker-rights',
    question: 'Right to emergency information?',
    answer: 'Workers must know emergency exits, assembly areas, and evacuation procedures',
    citation: 'Rule 1041, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'wr-15',
    topic: 'worker-rights',
    question: 'Can workers refuse to work overtime in hazardous conditions?',
    answer: 'Yes, if overtime increases exposure to unsafe conditions beyond safe limits',
    citation: 'RA 11058, Section 6',
    difficulty: 'hard',
  },

  // ===========================================
  // PENALTIES (10 cards)
  // ===========================================
  {
    id: 'pen-1',
    topic: 'penalties',
    question: 'Maximum daily fine for OSH violations?',
    answer: 'PHP 100,000 per day of non-compliance',
    citation: 'RA 11058, Section 12',
    difficulty: 'easy',
  },
  {
    id: 'pen-2',
    topic: 'penalties',
    question: 'Scheduled charges for death (under EC)?',
    answer: '6,000 days (compensation multiplier)',
    citation: 'EC Law, PD 626',
    difficulty: 'medium',
  },
  {
    id: 'pen-3',
    topic: 'penalties',
    question: 'Can employers face criminal liability for OSH violations?',
    answer: 'Yes, repeated violations or willful negligence leading to death can result in imprisonment',
    citation: 'RA 11058, Section 13',
    difficulty: 'hard',
  },
  {
    id: 'pen-4',
    topic: 'penalties',
    question: 'Penalty for operating without registration?',
    answer: 'Fine and/or work stoppage order',
    citation: 'Rule 1020, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'pen-5',
    topic: 'penalties',
    question: 'Can DOLE close a dangerous workplace?',
    answer: 'Yes, DOLE can issue Work Stoppage Order for imminent danger',
    citation: 'RA 11058, Section 11',
    difficulty: 'easy',
  },
  {
    id: 'pen-6',
    topic: 'penalties',
    question: 'Are administrative fines cumulative?',
    answer: 'Yes, PHP 100,000/day continues until violation is corrected',
    citation: 'RA 11058, Section 12',
    difficulty: 'medium',
  },
  {
    id: 'pen-7',
    topic: 'penalties',
    question: 'Penalty for retaliating against workers exercising OSH rights?',
    answer: 'Fine of PHP 50,000-100,000 and possible criminal charges',
    citation: 'RA 11058, Section 13',
    difficulty: 'hard',
  },
  {
    id: 'pen-8',
    topic: 'penalties',
    question: 'What is a Compliance Order?',
    answer: 'DOLE order requiring employer to correct violations within specified time',
    citation: 'RA 11058, Section 11',
    difficulty: 'easy',
  },
  {
    id: 'pen-9',
    topic: 'penalties',
    question: 'Who can impose OSH penalties?',
    answer: 'DOLE Regional Directors or authorized representatives',
    citation: 'RA 11058, Section 12',
    difficulty: 'medium',
  },
  {
    id: 'pen-10',
    topic: 'penalties',
    question: 'What happens after 3 violations in 3 years?',
    answer: 'Possible criminal prosecution of responsible officers',
    citation: 'RA 11058, Section 13',
    difficulty: 'hard',
  },

  // ===========================================
  // ENVIRONMENTAL STANDARDS (15 cards)
  // ===========================================
  {
    id: 'env-1',
    topic: 'environmental',
    question: 'Maximum noise exposure for 8 hours?',
    answer: '90 dBA',
    citation: 'Rule 1070.2, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'env-2',
    topic: 'environmental',
    question: 'Maximum noise exposure at 100 dBA?',
    answer: '2 hours',
    citation: 'Rule 1070.2, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'env-3',
    topic: 'environmental',
    question: 'Minimum illumination for offices?',
    answer: '300 lux',
    citation: 'Rule 1070.1, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'env-4',
    topic: 'environmental',
    question: 'Minimum illumination for detailed work (assembly)?',
    answer: '500-700 lux',
    citation: 'Rule 1070.1, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'env-5',
    topic: 'environmental',
    question: 'Minimum illumination for very detailed work?',
    answer: '1000+ lux',
    citation: 'Rule 1070.1, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'env-6',
    topic: 'environmental',
    question: 'Maximum noise exposure at 95 dBA?',
    answer: '4 hours',
    citation: 'Rule 1070.2, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'env-7',
    topic: 'environmental',
    question: 'Minimum workplace temperature?',
    answer: 'Not below 16°C for sedentary work',
    citation: 'Rule 1070, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'env-8',
    topic: 'environmental',
    question: 'When is hearing protection required?',
    answer: 'When noise exceeds 85 dBA for 8-hour exposure',
    citation: 'Rule 1070.2, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'env-9',
    topic: 'environmental',
    question: 'Minimum illumination for corridors?',
    answer: '100 lux',
    citation: 'Rule 1070.1, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'env-10',
    topic: 'environmental',
    question: 'Maximum noise exposure at 110 dBA?',
    answer: '30 minutes',
    citation: 'Rule 1070.2, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'env-11',
    topic: 'environmental',
    question: 'Ventilation rate per person in offices?',
    answer: 'Minimum 30 cubic meters of fresh air per person per hour',
    citation: 'Rule 1070.3, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'env-12',
    topic: 'environmental',
    question: 'Emergency lighting level?',
    answer: 'Minimum 10 lux for safe evacuation',
    citation: 'Rule 1070.1, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'env-13',
    topic: 'environmental',
    question: 'What is WBGT?',
    answer: 'Wet Bulb Globe Temperature - measures heat stress considering humidity, radiant heat, and air movement',
    citation: 'Rule 1070, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'env-14',
    topic: 'environmental',
    question: 'Noise halving rate?',
    answer: 'Every 5 dBA increase halves allowable exposure time',
    citation: 'Rule 1070.2, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'env-15',
    topic: 'environmental',
    question: 'Maximum dust exposure for nuisance particles?',
    answer: '10 mg/m³ for total dust, 5 mg/m³ for respirable',
    citation: 'Rule 1070, OSHS',
    difficulty: 'hard',
  },

  // ===========================================
  // PREMISES REQUIREMENTS (12 cards)
  // ===========================================
  {
    id: 'prem-1',
    topic: 'premises',
    question: 'Minimum ceiling height in workplaces?',
    answer: '2.7 meters (or 2.4 meters if air-conditioned)',
    citation: 'Rule 1060.1, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'prem-2',
    topic: 'premises',
    question: 'Minimum floor space per worker?',
    answer: '2 square meters of clear floor space',
    citation: 'Rule 1060.2, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'prem-3',
    topic: 'premises',
    question: 'Minimum stair width?',
    answer: '1.12 meters (44 inches)',
    citation: 'Rule 1060.3, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'prem-4',
    topic: 'premises',
    question: 'Maximum stair riser height?',
    answer: '20 cm (7.5 inches)',
    citation: 'Rule 1060.3, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'prem-5',
    topic: 'premises',
    question: 'Minimum toilet facilities ratio?',
    answer: '1 toilet per 25 workers (or fraction thereof)',
    citation: 'Rule 1060.4, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'prem-6',
    topic: 'premises',
    question: 'Minimum exit door width?',
    answer: '0.71 meters (28 inches) minimum',
    citation: 'Rule 1060.3, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'prem-7',
    topic: 'premises',
    question: 'Number of exits required?',
    answer: 'At least 2 exits for areas with 50+ occupants or over 93 sqm',
    citation: 'Rule 1060.3, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'prem-8',
    topic: 'premises',
    question: 'Maximum travel distance to exit?',
    answer: '45 meters (150 feet) for non-hazardous; 23 meters for hazardous',
    citation: 'Rule 1060.3, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'prem-9',
    topic: 'premises',
    question: 'What is required for floors with hazardous materials?',
    answer: 'Non-slip, impervious surfaces; adequate drainage; easy to clean',
    citation: 'Rule 1060.1, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'prem-10',
    topic: 'premises',
    question: 'Must exits be clearly marked?',
    answer: 'Yes, with illuminated EXIT signs visible from 30 meters',
    citation: 'Rule 1060.3, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'prem-11',
    topic: 'premises',
    question: 'Aisle width requirements?',
    answer: 'Minimum 1.12 meters for main aisles; 0.71 meters for secondary',
    citation: 'Rule 1060.2, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'prem-12',
    topic: 'premises',
    question: 'Handrail requirement for stairs?',
    answer: 'Required on both sides if width exceeds 1.12 meters',
    citation: 'Rule 1060.3, OSHS',
    difficulty: 'medium',
  },

  // ===========================================
  // PPE REQUIREMENTS (12 cards)
  // ===========================================
  {
    id: 'ppe-1',
    topic: 'ppe',
    question: 'At what height is fall protection required?',
    answer: '6 feet (1.8 meters) or higher',
    citation: 'Rule 1412.1, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ppe-2',
    topic: 'ppe',
    question: 'Who provides PPE to workers?',
    answer: 'Employer - free of charge',
    citation: 'RA 11058, Section 5; Rule 1080, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ppe-3',
    topic: 'ppe',
    question: 'What PPE is required for welding?',
    answer: 'Welding helmet with proper shade lens, gloves, apron, safety shoes',
    citation: 'Rule 1080, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ppe-4',
    topic: 'ppe',
    question: 'When is respiratory protection required?',
    answer: 'When engineering controls cannot reduce exposure below PEL',
    citation: 'Rule 1080.4, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ppe-5',
    topic: 'ppe',
    question: 'What is the hierarchy of hazard controls?',
    answer: 'Elimination > Substitution > Engineering > Administrative > PPE',
    citation: 'Rule 1080, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ppe-6',
    topic: 'ppe',
    question: 'Must PPE be properly fitted?',
    answer: 'Yes, employer must ensure proper fit and train workers on use',
    citation: 'Rule 1080.2, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ppe-7',
    topic: 'ppe',
    question: 'Who is responsible for PPE maintenance?',
    answer: 'Employer must maintain and replace damaged PPE; workers must care for it',
    citation: 'Rule 1080.3, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ppe-8',
    topic: 'ppe',
    question: 'What is the minimum safety shoe standard?',
    answer: 'Steel toe cap, slip-resistant sole, appropriate for hazards',
    citation: 'Rule 1080, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'ppe-9',
    topic: 'ppe',
    question: 'When are safety glasses required?',
    answer: 'When there is risk of flying particles, splashes, or harmful radiation',
    citation: 'Rule 1080.1, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'ppe-10',
    topic: 'ppe',
    question: 'Hard hat color for visitors?',
    answer: 'White (common practice, not strictly mandated)',
    citation: 'Industry Practice',
    difficulty: 'easy',
  },
  {
    id: 'ppe-11',
    topic: 'ppe',
    question: 'What is IDLH?',
    answer: 'Immediately Dangerous to Life or Health - requires supplied air respirator',
    citation: 'Rule 1080.4, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'ppe-12',
    topic: 'ppe',
    question: 'Fall protection options?',
    answer: 'Guardrails, safety nets, personal fall arrest systems (harness)',
    citation: 'Rule 1412, OSHS',
    difficulty: 'medium',
  },

  // ===========================================
  // REGISTRATION (8 cards)
  // ===========================================
  {
    id: 'reg-1',
    topic: 'registration',
    question: 'When must new establishments register?',
    answer: '30 days before start of operations',
    citation: 'Rule 1020.2, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'reg-2',
    topic: 'registration',
    question: 'What form is used for establishment registration?',
    answer: 'DOLE-BWC-IP-3 (Registration of Establishment)',
    citation: 'Rule 1020, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'reg-3',
    topic: 'registration',
    question: 'Where do establishments register?',
    answer: 'DOLE Regional Office where workplace is located',
    citation: 'Rule 1020.2, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'reg-4',
    topic: 'registration',
    question: 'Is registration free?',
    answer: 'Yes, no fees for workplace registration',
    citation: 'Rule 1020, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'reg-5',
    topic: 'registration',
    question: 'What triggers re-registration?',
    answer: 'Change in ownership, location, business name, or nature of business',
    citation: 'Rule 1020.3, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'reg-6',
    topic: 'registration',
    question: 'Must contractors register separately?',
    answer: 'Yes, each contractor must register their own establishment',
    citation: 'Rule 1020.2, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'reg-7',
    topic: 'registration',
    question: 'What is the Rule 1020 certificate?',
    answer: 'Certificate of Registration issued by DOLE after successful registration',
    citation: 'Rule 1020.4, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'reg-8',
    topic: 'registration',
    question: 'Must construction projects register?',
    answer: 'Yes, each construction project must be registered before work begins',
    citation: 'D.O. 13, s. 1998',
    difficulty: 'medium',
  },

  // ===========================================
  // CONFINED SPACES (10 cards)
  // ===========================================
  {
    id: 'cs-1',
    topic: 'confined-spaces',
    question: 'Safe oxygen level in confined space?',
    answer: '19.5% to 23.5%',
    citation: 'Rule 1087, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'cs-2',
    topic: 'confined-spaces',
    question: 'What is a confined space?',
    answer: 'Space with limited entry/exit, not designed for continuous occupancy, potential for hazardous atmosphere',
    citation: 'Rule 1087.1, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'cs-3',
    topic: 'confined-spaces',
    question: 'Is a standby person (watcher) required for confined space entry?',
    answer: 'Yes, at least one qualified person must remain outside',
    citation: 'Rule 1087.4, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'cs-4',
    topic: 'confined-spaces',
    question: 'What must be tested before confined space entry?',
    answer: 'Oxygen, flammable gases, toxic gases (in that order)',
    citation: 'Rule 1087.3, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'cs-5',
    topic: 'confined-spaces',
    question: 'What is a permit-required confined space?',
    answer: 'One with serious hazards requiring written entry permit and special procedures',
    citation: 'Rule 1087.2, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'cs-6',
    topic: 'confined-spaces',
    question: 'Maximum LEL for confined space entry?',
    answer: '10% of Lower Explosive Limit (LEL)',
    citation: 'Rule 1087.3, OSHS',
    difficulty: 'hard',
  },
  {
    id: 'cs-7',
    topic: 'confined-spaces',
    question: 'When is continuous air monitoring required?',
    answer: 'When atmospheric hazards may develop during work',
    citation: 'Rule 1087.3, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'cs-8',
    topic: 'confined-spaces',
    question: 'What is lockout/tagout (LOTO)?',
    answer: 'Procedure to isolate energy sources before confined space entry or maintenance',
    citation: 'Rule 1087.5, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'cs-9',
    topic: 'confined-spaces',
    question: 'Rescue equipment requirement?',
    answer: 'Must have rescue equipment ready and trained rescue personnel available',
    citation: 'Rule 1087.6, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'cs-10',
    topic: 'confined-spaces',
    question: 'Entry permit validity?',
    answer: 'Only for the specific entry; new permit needed for each entry',
    citation: 'Rule 1087.2, OSHS',
    difficulty: 'medium',
  },

  // ===========================================
  // HAZARDOUS MATERIALS (12 cards)
  // ===========================================
  {
    id: 'haz-1',
    topic: 'hazardous',
    question: 'What is the hierarchy of control for hazardous materials?',
    answer: 'Elimination > Substitution > Engineering > Administrative > PPE',
    citation: 'Rule 1090, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'haz-2',
    topic: 'hazardous',
    question: 'What is the "acid rule" for dilution?',
    answer: 'Always add acid to water, never water to acid (A to W)',
    citation: 'Rule 1090, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'haz-3',
    topic: 'hazardous',
    question: 'What is SDS/MSDS?',
    answer: 'Safety Data Sheet / Material Safety Data Sheet - contains chemical hazard information',
    citation: 'Rule 1090, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'haz-4',
    topic: 'hazardous',
    question: 'How many sections in GHS-compliant SDS?',
    answer: '16 sections',
    citation: 'GHS / Rule 1090',
    difficulty: 'medium',
  },
  {
    id: 'haz-5',
    topic: 'hazardous',
    question: 'What is GHS?',
    answer: 'Globally Harmonized System for classification and labeling of chemicals',
    citation: 'D.O. 136, s. 2014',
    difficulty: 'easy',
  },
  {
    id: 'haz-6',
    topic: 'hazardous',
    question: 'Chemical storage - incompatible substances?',
    answer: 'Must be stored separately with proper distance or barriers',
    citation: 'Rule 1090.4, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'haz-7',
    topic: 'hazardous',
    question: 'What is TLV?',
    answer: 'Threshold Limit Value - maximum safe airborne concentration',
    citation: 'Rule 1090, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'haz-8',
    topic: 'hazardous',
    question: 'What is PEL?',
    answer: 'Permissible Exposure Limit - legal maximum exposure level',
    citation: 'Rule 1090, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'haz-9',
    topic: 'hazardous',
    question: 'Chemical labeling requirements?',
    answer: 'Product name, hazard pictograms, signal word, hazard statements, precautionary statements',
    citation: 'D.O. 136, s. 2014',
    difficulty: 'hard',
  },
  {
    id: 'haz-10',
    topic: 'hazardous',
    question: 'Flammable liquid storage requirements?',
    answer: 'Fire-rated storage, proper ventilation, grounding for static, no ignition sources',
    citation: 'Rule 1090.4, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'haz-11',
    topic: 'hazardous',
    question: 'What is a carcinogen?',
    answer: 'A substance capable of causing cancer',
    citation: 'Rule 1090, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'haz-12',
    topic: 'hazardous',
    question: 'Spill response priority?',
    answer: 'Protect people > Stop source > Contain spill > Clean up',
    citation: 'Rule 1090, OSHS',
    difficulty: 'medium',
  },

  // ===========================================
  // HEALTH SERVICES (11 cards)
  // ===========================================
  {
    id: 'hs-1',
    topic: 'health-services',
    question: 'First-aider ratio for non-hazardous workplace?',
    answer: '1 trained first-aider per 50 workers (or fraction)',
    citation: 'Rule 1960.3, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hs-2',
    topic: 'health-services',
    question: 'When is a full-time nurse required?',
    answer: 'When there are 51-200 workers in hazardous workplace',
    citation: 'Rule 1960.1, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hs-3',
    topic: 'health-services',
    question: 'When is a part-time physician required?',
    answer: 'When there are 51-200 workers, or full-time for 201+ workers',
    citation: 'Rule 1960.2, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hs-4',
    topic: 'health-services',
    question: 'What is OHS (Occupational Health Service)?',
    answer: 'On-site or contracted health services for employee medical needs',
    citation: 'Rule 1960, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hs-5',
    topic: 'health-services',
    question: 'Pre-employment medical exam required?',
    answer: 'Yes, for hazardous work; recommended for all employment',
    citation: 'Rule 1960.4, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hs-6',
    topic: 'health-services',
    question: 'How often are periodic medical exams required?',
    answer: 'At least annually for workers exposed to hazards',
    citation: 'Rule 1960.4, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hs-7',
    topic: 'health-services',
    question: 'First aid kit requirements?',
    answer: 'Must have first aid supplies accessible in all work areas; contents based on hazards',
    citation: 'Rule 1960.3, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hs-8',
    topic: 'health-services',
    question: 'Emergency treatment room required when?',
    answer: 'For workplaces with 200+ workers or high-hazard operations',
    citation: 'Rule 1960.1, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hs-9',
    topic: 'health-services',
    question: 'Who pays for occupational health exams?',
    answer: 'Employer pays for all required medical examinations',
    citation: 'Rule 1960.4, OSHS',
    difficulty: 'easy',
  },
  {
    id: 'hs-10',
    topic: 'health-services',
    question: 'First-aider training hours?',
    answer: 'Minimum 16 hours training from accredited provider',
    citation: 'Rule 1960.3, OSHS',
    difficulty: 'medium',
  },
  {
    id: 'hs-11',
    topic: 'health-services',
    question: 'Medical records retention?',
    answer: 'Must be kept for at least 30 years after employment ends',
    citation: 'Rule 1960.5, OSHS',
    difficulty: 'hard',
  },
];

// ============================================
// QUIZ QUESTIONS - 50+ questions
// ============================================

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // Safety Officers
  {
    id: 'quiz-so-1',
    topic: 'safety-officers',
    question: 'A non-hazardous workplace with 175 workers requires which SO level?',
    options: ['SO1', 'SO2', 'SO3', 'SO4'],
    correctIndex: 1,
    explanation: 'Non-hazardous 51-200 workers requires Part-time SO2.',
    citation: 'Rule 1033, OSHS',
  },
  {
    id: 'quiz-so-2',
    topic: 'safety-officers',
    question: 'How many hours of training does SO3 require?',
    options: ['40 hours', '80 hours', '120 hours', '160 hours'],
    correctIndex: 1,
    explanation: 'SO3 requires 80 hours (40 BOSH + 40 COSH).',
    citation: 'Rule 1030, OSHS',
  },
  {
    id: 'quiz-so-3',
    topic: 'safety-officers',
    question: 'Safety Officer refresher training is required every:',
    options: ['1 year', '2 years', '3 years', '5 years'],
    correctIndex: 1,
    explanation: 'Refresher training is required every 2 years.',
    citation: 'Rule 1030.4, OSHS',
  },
  {
    id: 'quiz-so-4',
    topic: 'safety-officers',
    question: 'A hazardous workplace with 75 workers requires:',
    options: ['Part-time SO1', 'Part-time SO2', 'Full-time SO2', 'Full-time SO3'],
    correctIndex: 2,
    explanation: 'Hazardous 51-200 workers requires Full-time SO2.',
    citation: 'Rule 1033, OSHS',
  },
  {
    id: 'quiz-so-5',
    topic: 'safety-officers',
    question: 'BOSH training consists of how many hours?',
    options: ['8 hours', '16 hours', '40 hours', '80 hours'],
    correctIndex: 2,
    explanation: 'BOSH (Basic Occupational Safety and Health) is 40 hours.',
    citation: 'Rule 1030, OSHS',
  },

  // Committee
  {
    id: 'quiz-hsc-1',
    topic: 'committee',
    question: 'A Type C Health and Safety Committee has how many members?',
    options: ['4 members', '6 members', '8 members', '12 members'],
    correctIndex: 1,
    explanation: 'Type C = 6 members (3 management, 3 workers).',
    citation: 'Rule 1040, OSHS',
  },
  {
    id: 'quiz-hsc-2',
    topic: 'committee',
    question: 'Health and Safety Committees must meet at least:',
    options: ['Weekly', 'Bi-weekly', 'Monthly', 'Quarterly'],
    correctIndex: 2,
    explanation: 'HSC must meet at least once a month.',
    citation: 'Rule 1040.6, OSHS',
  },
  {
    id: 'quiz-hsc-3',
    topic: 'committee',
    question: 'Committees must be reorganized every:',
    options: ['January', 'June', 'When needed', 'Every 2 years'],
    correctIndex: 0,
    explanation: 'Committees are reorganized every January.',
    citation: 'Rule 1040.5, OSHS',
  },
  {
    id: 'quiz-hsc-4',
    topic: 'committee',
    question: 'A non-hazardous workplace with 300 workers needs which HSC type?',
    options: ['Type B', 'Type C', 'Type D', 'Type E'],
    correctIndex: 1,
    explanation: 'Non-hazardous 201-500 workers = Type C (6 members).',
    citation: 'Rule 1040, OSHS',
  },
  {
    id: 'quiz-hsc-5',
    topic: 'committee',
    question: 'Type E Committee has how many worker representatives?',
    options: ['4', '5', '6', '8'],
    correctIndex: 2,
    explanation: 'Type E = 12 total (6 management + 6 workers).',
    citation: 'Rule 1040, OSHS',
  },

  // Reporting
  {
    id: 'quiz-ar-1',
    topic: 'reporting',
    question: 'Fatal accidents must be reported to DOLE within:',
    options: ['Immediately', '24 hours', '48 hours', '1 week'],
    correctIndex: 1,
    explanation: 'Fatal accidents require 24-hour notification to DOLE.',
    citation: 'Rule 1050.1, OSHS',
  },
  {
    id: 'quiz-ar-2',
    topic: 'reporting',
    question: 'Monthly WAIR is due on the:',
    options: ['15th', '20th', '25th', '30th'],
    correctIndex: 1,
    explanation: 'WAIR is due on the 20th of the following month.',
    citation: 'Rule 1050, OSHS',
  },
  {
    id: 'quiz-ar-3',
    topic: 'reporting',
    question: 'Annual accident report is due every:',
    options: ['December 31', 'January 30', 'February 28', 'March 15'],
    correctIndex: 1,
    explanation: 'Annual report is due January 30 of the following year.',
    citation: 'Rule 1050, OSHS',
  },
  {
    id: 'quiz-ar-4',
    topic: 'reporting',
    question: 'How long must accident records be kept?',
    options: ['1 year', '3 years', '5 years', '10 years'],
    correctIndex: 2,
    explanation: 'Accident records must be retained for at least 5 years.',
    citation: 'Rule 1050.4, OSHS',
  },
  {
    id: 'quiz-ar-5',
    topic: 'reporting',
    question: 'If there are no accidents in a month, employers should:',
    options: ['Skip the WAIR', 'Submit a nil report', 'File annually only', 'Notify DOLE verbally'],
    correctIndex: 1,
    explanation: 'A nil report must be submitted even with zero accidents.',
    citation: 'Rule 1050, OSHS',
  },

  // Worker Rights
  {
    id: 'quiz-wr-1',
    topic: 'worker-rights',
    question: 'Who pays for Personal Protective Equipment?',
    options: ['Worker', 'Shared 50-50', 'Employer', 'Government subsidy'],
    correctIndex: 2,
    explanation: 'Employer must provide PPE free of charge.',
    citation: 'RA 11058, Section 5',
  },
  {
    id: 'quiz-wr-2',
    topic: 'worker-rights',
    question: 'Can a worker refuse unsafe work?',
    options: ['No', 'Yes, with pay protection', 'Only with union approval', 'Only after filing complaint'],
    correctIndex: 1,
    explanation: 'Workers can refuse imminent danger without retaliation.',
    citation: 'RA 11058, Section 6',
  },
  {
    id: 'quiz-wr-3',
    topic: 'worker-rights',
    question: 'Contractual workers have OSH rights:',
    options: ['Different from regular', 'Same as regular', 'Only basic rights', 'No rights'],
    correctIndex: 1,
    explanation: 'All workers have equal OSH rights regardless of status.',
    citation: 'RA 11058, Section 4',
  },
  {
    id: 'quiz-wr-4',
    topic: 'worker-rights',
    question: 'What happens if an employer retaliates against a worker for reporting?',
    options: ['No penalty', 'Warning only', 'Fine PHP 50,000-100,000', 'Mediation required'],
    correctIndex: 2,
    explanation: 'Retaliation carries fine of PHP 50,000-100,000 and possible criminal charges.',
    citation: 'RA 11058, Section 13',
  },
  {
    id: 'quiz-wr-5',
    topic: 'worker-rights',
    question: 'The "Right to Know" means workers must be informed about:',
    options: ['Salaries only', 'Company profits', 'Workplace hazards', 'Union activities'],
    correctIndex: 2,
    explanation: 'Right to know = informed about hazards, risks, and safety measures.',
    citation: 'RA 11058, Section 6',
  },

  // Penalties
  {
    id: 'quiz-pen-1',
    topic: 'penalties',
    question: 'Maximum daily fine for OSH violations under RA 11058:',
    options: ['PHP 10,000', 'PHP 50,000', 'PHP 100,000', 'PHP 500,000'],
    correctIndex: 2,
    explanation: 'Maximum fine is PHP 100,000 per day of non-compliance.',
    citation: 'RA 11058, Section 12',
  },
  {
    id: 'quiz-pen-2',
    topic: 'penalties',
    question: 'A Work Stoppage Order can be issued for:',
    options: ['Minor violations', 'Imminent danger', 'Late reports only', 'First offense'],
    correctIndex: 1,
    explanation: 'WSO is issued when there is imminent danger to workers.',
    citation: 'RA 11058, Section 11',
  },
  {
    id: 'quiz-pen-3',
    topic: 'penalties',
    question: 'Criminal prosecution may occur after how many violations in 3 years?',
    options: ['1', '2', '3', '5'],
    correctIndex: 2,
    explanation: 'After 3 violations in 3 years, criminal prosecution is possible.',
    citation: 'RA 11058, Section 13',
  },
  {
    id: 'quiz-pen-4',
    topic: 'penalties',
    question: 'Scheduled charges for death under Employees Compensation:',
    options: ['3,000 days', '4,000 days', '5,000 days', '6,000 days'],
    correctIndex: 3,
    explanation: 'Death = 6,000 days compensation multiplier.',
    citation: 'PD 626',
  },
  {
    id: 'quiz-pen-5',
    topic: 'penalties',
    question: 'Daily fines continue until:',
    options: ['Appeal is filed', 'Violation is corrected', '30 days maximum', 'Court hearing'],
    correctIndex: 1,
    explanation: 'Fines are cumulative until the violation is corrected.',
    citation: 'RA 11058, Section 12',
  },

  // Environmental
  {
    id: 'quiz-env-1',
    topic: 'environmental',
    question: 'Maximum noise exposure for 8 hours continuous work:',
    options: ['80 dBA', '85 dBA', '90 dBA', '95 dBA'],
    correctIndex: 2,
    explanation: '90 dBA is the maximum for 8-hour exposure.',
    citation: 'Rule 1070.2, OSHS',
  },
  {
    id: 'quiz-env-2',
    topic: 'environmental',
    question: 'At 100 dBA, maximum allowable exposure is:',
    options: ['4 hours', '2 hours', '1 hour', '30 minutes'],
    correctIndex: 1,
    explanation: '100 dBA = 2 hours maximum (5 dBA halving rate).',
    citation: 'Rule 1070.2, OSHS',
  },
  {
    id: 'quiz-env-3',
    topic: 'environmental',
    question: 'Minimum office illumination requirement:',
    options: ['100 lux', '200 lux', '300 lux', '500 lux'],
    correctIndex: 2,
    explanation: 'Offices require minimum 300 lux illumination.',
    citation: 'Rule 1070.1, OSHS',
  },
  {
    id: 'quiz-env-4',
    topic: 'environmental',
    question: 'Hearing protection is recommended above:',
    options: ['80 dBA', '85 dBA', '90 dBA', '95 dBA'],
    correctIndex: 1,
    explanation: 'Hearing protection recommended when noise exceeds 85 dBA.',
    citation: 'Rule 1070.2, OSHS',
  },
  {
    id: 'quiz-env-5',
    topic: 'environmental',
    question: 'Emergency lighting minimum level:',
    options: ['5 lux', '10 lux', '20 lux', '50 lux'],
    correctIndex: 1,
    explanation: 'Emergency lighting must provide minimum 10 lux.',
    citation: 'Rule 1070.1, OSHS',
  },

  // Premises
  {
    id: 'quiz-prem-1',
    topic: 'premises',
    question: 'Minimum ceiling height for workplaces:',
    options: ['2.4m', '2.7m', '3.0m', '3.5m'],
    correctIndex: 1,
    explanation: '2.7m standard; 2.4m if air-conditioned.',
    citation: 'Rule 1060.1, OSHS',
  },
  {
    id: 'quiz-prem-2',
    topic: 'premises',
    question: 'Minimum floor space per worker:',
    options: ['1 sqm', '2 sqm', '3 sqm', '4 sqm'],
    correctIndex: 1,
    explanation: 'Each worker needs at least 2 square meters of clear floor space.',
    citation: 'Rule 1060.2, OSHS',
  },
  {
    id: 'quiz-prem-3',
    topic: 'premises',
    question: 'Toilet ratio requirement:',
    options: ['1:15 workers', '1:25 workers', '1:50 workers', '1:100 workers'],
    correctIndex: 1,
    explanation: 'One toilet per 25 workers or fraction thereof.',
    citation: 'Rule 1060.4, OSHS',
  },
  {
    id: 'quiz-prem-4',
    topic: 'premises',
    question: 'Two exits required when occupancy exceeds:',
    options: ['25 persons', '50 persons', '75 persons', '100 persons'],
    correctIndex: 1,
    explanation: 'Areas with 50+ occupants need at least 2 exits.',
    citation: 'Rule 1060.3, OSHS',
  },
  {
    id: 'quiz-prem-5',
    topic: 'premises',
    question: 'Maximum travel distance to exit in non-hazardous area:',
    options: ['23m', '30m', '45m', '60m'],
    correctIndex: 2,
    explanation: '45 meters for non-hazardous; 23m for hazardous.',
    citation: 'Rule 1060.3, OSHS',
  },

  // PPE
  {
    id: 'quiz-ppe-1',
    topic: 'ppe',
    question: 'Fall protection required at what height?',
    options: ['4 feet', '6 feet', '8 feet', '10 feet'],
    correctIndex: 1,
    explanation: 'Fall protection required at 6 feet (1.8m) or higher.',
    citation: 'Rule 1412.1, OSHS',
  },
  {
    id: 'quiz-ppe-2',
    topic: 'ppe',
    question: 'PPE is the ___ level in hierarchy of controls:',
    options: ['First', 'Second', 'Third', 'Last'],
    correctIndex: 3,
    explanation: 'PPE is the last resort after elimination, substitution, engineering, administrative controls.',
    citation: 'Rule 1080, OSHS',
  },
  {
    id: 'quiz-ppe-3',
    topic: 'ppe',
    question: 'If PPE is damaged, who must replace it?',
    options: ['Worker', 'Employer', 'Shared cost', 'Insurance'],
    correctIndex: 1,
    explanation: 'Employer must maintain and replace damaged PPE.',
    citation: 'Rule 1080.3, OSHS',
  },
  {
    id: 'quiz-ppe-4',
    topic: 'ppe',
    question: 'IDLH stands for:',
    options: ['Immediate Danger Level High', 'Immediately Dangerous to Life or Health', 'Internal Danger Limit Hazard', 'Industrial Danger Level High'],
    correctIndex: 1,
    explanation: 'IDLH = Immediately Dangerous to Life or Health.',
    citation: 'Rule 1080.4, OSHS',
  },
  {
    id: 'quiz-ppe-5',
    topic: 'ppe',
    question: 'First step in hierarchy of hazard controls:',
    options: ['PPE', 'Administrative controls', 'Engineering controls', 'Elimination'],
    correctIndex: 3,
    explanation: 'Elimination is the most effective control.',
    citation: 'Rule 1080, OSHS',
  },

  // Registration
  {
    id: 'quiz-reg-1',
    topic: 'registration',
    question: 'New establishments must register with DOLE within:',
    options: ['Before operations', '30 days before', '30 days after', '1 year'],
    correctIndex: 1,
    explanation: 'Registration required 30 days before start of operations.',
    citation: 'Rule 1020.2, OSHS',
  },
  {
    id: 'quiz-reg-2',
    topic: 'registration',
    question: 'Registration form for establishments:',
    options: ['DOLE-BWC-IP-1', 'DOLE-BWC-IP-3', 'DOLE-BWC-IP-6', 'DOLE Form 1'],
    correctIndex: 1,
    explanation: 'DOLE-BWC-IP-3 is the Registration of Establishment form.',
    citation: 'Rule 1020, OSHS',
  },
  {
    id: 'quiz-reg-3',
    topic: 'registration',
    question: 'Registration with DOLE is:',
    options: ['Fee-based', 'Free', 'By appointment only', 'Online only'],
    correctIndex: 1,
    explanation: 'Workplace registration is free of charge.',
    citation: 'Rule 1020, OSHS',
  },

  // Confined Spaces
  {
    id: 'quiz-cs-1',
    topic: 'confined-spaces',
    question: 'Safe oxygen level in confined space:',
    options: ['15% - 18%', '19.5% - 23.5%', '21% - 25%', '18% - 22%'],
    correctIndex: 1,
    explanation: 'Safe oxygen range is 19.5% to 23.5%.',
    citation: 'Rule 1087, OSHS',
  },
  {
    id: 'quiz-cs-2',
    topic: 'confined-spaces',
    question: 'A standby person (watcher) is required for confined space entry:',
    options: ['Never', 'Sometimes', 'Always', 'Only in emergencies'],
    correctIndex: 2,
    explanation: 'At least one qualified standby person must remain outside.',
    citation: 'Rule 1087.4, OSHS',
  },
  {
    id: 'quiz-cs-3',
    topic: 'confined-spaces',
    question: 'Atmospheric testing order: first test for:',
    options: ['Toxic gases', 'Flammable gases', 'Oxygen', 'Carbon monoxide'],
    correctIndex: 2,
    explanation: 'Test order: Oxygen > Flammable > Toxic.',
    citation: 'Rule 1087.3, OSHS',
  },

  // Hazardous Materials
  {
    id: 'quiz-haz-1',
    topic: 'hazardous',
    question: 'When diluting acid, always add:',
    options: ['Water to acid', 'Acid to water', 'Both together', 'Acid first, then water slowly'],
    correctIndex: 1,
    explanation: 'Always add Acid to Water (A to W), never water to acid.',
    citation: 'Rule 1090, OSHS',
  },
  {
    id: 'quiz-haz-2',
    topic: 'hazardous',
    question: 'GHS-compliant Safety Data Sheets have how many sections?',
    options: ['8', '12', '16', '20'],
    correctIndex: 2,
    explanation: 'GHS SDS has 16 standardized sections.',
    citation: 'D.O. 136, s. 2014',
  },
  {
    id: 'quiz-haz-3',
    topic: 'hazardous',
    question: 'TLV stands for:',
    options: ['Total Limit Value', 'Threshold Limit Value', 'Toxic Level Value', 'Time Limit Variable'],
    correctIndex: 1,
    explanation: 'TLV = Threshold Limit Value (maximum safe concentration).',
    citation: 'Rule 1090, OSHS',
  },

  // Health Services
  {
    id: 'quiz-hs-1',
    topic: 'health-services',
    question: 'First-aider ratio for non-hazardous workplace:',
    options: ['1:25', '1:50', '1:75', '1:100'],
    correctIndex: 1,
    explanation: 'One trained first-aider per 50 workers.',
    citation: 'Rule 1960.3, OSHS',
  },
  {
    id: 'quiz-hs-2',
    topic: 'health-services',
    question: 'Medical records must be kept for at least:',
    options: ['5 years', '10 years', '20 years', '30 years'],
    correctIndex: 3,
    explanation: 'Medical records must be retained for 30 years after employment ends.',
    citation: 'Rule 1960.5, OSHS',
  },
  {
    id: 'quiz-hs-3',
    topic: 'health-services',
    question: 'Who pays for required occupational health exams?',
    options: ['Worker', 'Employer', 'SSS', 'PhilHealth'],
    correctIndex: 1,
    explanation: 'Employer must pay for all required medical examinations.',
    citation: 'Rule 1960.4, OSHS',
  },
];

// Helper function to get flashcards by topic
export function getFlashcardsByTopic(topic: StudyTopic): Flashcard[] {
  return FLASHCARDS.filter(card => card.topic === topic);
}

// Helper function to get quiz questions by topic
export function getQuizQuestionsByTopic(topic: StudyTopic): QuizQuestion[] {
  return QUIZ_QUESTIONS.filter(q => q.topic === topic);
}

// Helper to get all topics with counts
export function getTopicStats(): Record<StudyTopic, { flashcards: number; quizzes: number }> {
  const topics = Object.keys(TOPIC_INFO) as StudyTopic[];
  return topics.reduce((acc, topic) => {
    acc[topic] = {
      flashcards: FLASHCARDS.filter(c => c.topic === topic).length,
      quizzes: QUIZ_QUESTIONS.filter(q => q.topic === topic).length,
    };
    return acc;
  }, {} as Record<StudyTopic, { flashcards: number; quizzes: number }>);
}

// Helper to shuffle array
export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
