// Rule 1090 - Hazardous Materials
// OSHS Original

export const RULE_1090 = {
  ruleNumber: '1090',
  title: 'Hazardous Materials',
  amendments: [],

  // ===========================================
  // SECTION 1091: SCOPE
  // ===========================================
  scope: {
    section: '1091',
    applies: 'All workplaces where hazardous substances in solid, liquid, or gaseous forms are:',
    activities: [
      'Manufactured',
      'Handled',
      'Used',
    ],
    alsoApplies: 'Where flammable, irritating, offensive or toxic dusts, fibers, gases, mists or vapors are generated or released in quantities injurious to health',
  },

  // ===========================================
  // SECTION 1092: DEFINITIONS
  // ===========================================
  definitions: {
    section: '1092',

    hazardousMaterials: {
      term: 'Hazardous materials or substances',
      definition: 'Substances in solid, liquid or gaseous forms known to constitute poison, fire, explosion or health hazard',
    },

    corrosive: {
      term: 'Corrosive',
      onInanimateSurface: 'Causes wearing away, gradual changing or destroying of texture/substance of metal, glass, wood',
      onLivingTissue: 'Causes more or less severe destruction of tissue by chemical action',
    },

    hot: {
      term: 'Hot',
      definition: 'Material or substance possessing or characterized by relatively high temperature',
    },

    gases: {
      term: 'Gases',
      definition: 'Normally aeroform fluid with neither shape nor specific volume, tends to expand indefinitely, can be changed to liquid/solid by increased pressure or decreased temperature',
    },

    fumes: {
      term: 'Fumes',
      definition: 'Suspended solid particles generated by condensation from gaseous state, generally after volatilization from molten metals',
    },

    vapor: {
      term: 'Vapor',
      definition: 'Gaseous form of substances normally in liquid or solid state, can be changed by increasing pressure or decreasing temperature',
    },

    mists: {
      term: 'Mists',
      definition: 'Suspended liquid droplets generated by condensation from gaseous to liquid state or by breaking up liquid (atomizing, foaming, splashing)',
    },

    fibers: {
      term: 'Fibers',
      definition: 'Any tough solid substance composed of thread-like tissue, whether mineral, vegetable, or animal origin',
    },

    dust: {
      term: 'Dust',
      definition: 'Solid particles capable of being blown about or suspended in air, generated by handling, crushing, cutting, drilling, grinding, rapid impact, spraying, detonations, or disintegration',
    },

    toxic: {
      term: 'Toxic',
      definition: 'Acting or likely to act as a poison, or may chemically produce injurious or deadly effect',
    },

    irritating: {
      term: 'Irritating',
      definition: 'Causing undue sensitiveness of an organ or part of the body',
    },
  },

  // ===========================================
  // SECTION 1093: GENERAL RULES
  // ===========================================
  generalRules: {
    section: '1093',

    reductionOfHazards: {
      subsection: '1093.01',
      principle: 'When practicable, harmless substances shall be substituted for hazardous substances',
      alternative: 'Process shall be revised to reduce worker exposure to hazards',
    },

    controlOfProcesses: {
      subsection: '1093.02',
      methods: [
        'Separate rooms/building with minimum workers, suitable PPE, and trained personnel',
        'Air-tight enclosure to prevent personal contact and escape of contaminants',
        'Local exhaust ventilation (fume chambers, suction hoods) at point of origin',
        'General ventilation to keep concentration within safe limits',
      ],
    },

    ppe: {
      subsection: '1093.03',
      requirement: 'Workers shall be provided with and use PPE per Rule 1080',
      supplementary: 'PPE used to supplement control methods when they cannot adequately eliminate hazard',
    },

    markingOfContainers: {
      subsection: '1093.04',
      requirement: 'All containers with hazardous substances shall be properly labelled',
      prohibition: 'No employer shall accept unlabelled containers for use, handling, or storage',

      labelRequirements: {
        mustContain: [
          'Symbol of relevant hazard category (explosive, flammable, oxidizing, toxic, corrosive, radioactive)',
          'Trade name (may be used in addition to chemical name)',
          'Description of principal risk(s)',
          'Statement of necessary precautions',
          'First-aid or emergency measures (if necessary)',
        ],
        shape: 'Rectangular',
        symbolSize: 'In relation to package/container size',
        text: 'Adequate size to be clear and legible, black on white background',
      },

      markingMethod: {
        method: 'Lithographed, press-printed, or engraved on paper label securely attached',
        largeContainers: 'Over 18.92 liters (5 gallons): May use stencilled/stamped letters min 2.54 cm (1 in.) height',
        weatherResistant: 'Shall not be defaced by rain or weather elements',
      },

      responsibility: {
        localManufacturer: 'Manufacturer responsible for correct labelling',
        imported: 'Importer, distributor, or retailer responsible',
        redistribution: 'Distributors, wholesalers, or retailers responsible when no manufacturer contact',
        workplace: 'Employer responsible for labelling substances for workplace use',
        transfer: 'Employer responsible when transferring to other containers',
        unlabelled: 'Employer shall properly label unlabelled substances received',
      },

      smallContainers: {
        retain: ['Symbol', 'Product name', 'Statement of hazards'],
        mayOmit: 'Precautionary measures if clearly indicated in symbol and hazard statement',
        include: 'Precautionary measures for additional hazards',
      },
    },

    testingOfAtmosphere: {
      subsection: '1093.05',
      frequency: 'Periodically as necessary, but not longer than annually',
      purpose: 'Ensure concentration within threshold limit values (Rule 1070)',
    },

    ventilationEquipment: {
      subsection: '1093.06',
      requirement: 'Inspect and test periodically for safe and efficient operational performance',
    },

    dustAccumulation: {
      subsection: '1093.07',
      design: 'Structure/equipment designed to minimize dust accumulation surfaces',
      cleaning: 'Frequently cleaned',
      flammableDust: {
        daily: 'Remove from floors, equipment, horizontal surfaces (preferably vacuum)',
        weekly: 'All fixtures, ledges, projections, bearings, sidewalks, ceilings cleaned',
      },
      floors: {
        requirements: ['Smooth', 'Impervious', 'Easy to clean'],
        prohibition: 'Not covered with loose sheets or metal under which dust can accumulate',
      },
    },

    cleaning: {
      subsection: '1093.08',
      when: 'Where toxic and irritating substances are handled, manufactured, or used',
      what: 'Floors, walls, structural surfaces, work benches, tables, equipment',
      how: 'Vacuum cleaning, wet brushing, or sweeping',
      timing: 'Daily, outside of working hours',
    },

    emergencyPrecautions: {
      subsection: '1093.09',
      warningDevices: 'Suitable warning devices to alert personnel of dangerous liberation of substances',
      training: 'Workers trained on control procedures, pollution elimination, and orderly evacuation',
    },

    workingClothing: {
      subsection: '1093.10',
      requirement: 'Appropriate protective clothing including head covering',
      rules: [
        'Remove before eating or leaving premises, kept in designated places',
        'Not taken out of factory for any purpose',
        'Maintained in good condition, washed/cleaned at least once a week',
      ],
    },

    spillage: {
      subsection: '1093.11',
      requirement: 'Remove as quickly as possible by best technical and scientific means',
    },

    instruction: {
      subsection: '1093.12',
      requirement: 'All workers thoroughly informed of health hazards and protective measures',
    },

    meals: {
      subsection: '1093.13',
      prohibition: 'Introduction, preparation, and consumption of food, drink, and tobacco in workroom prohibited',
    },

    personalCleanliness: {
      subsection: '1093.14',
      requirement: 'Workers exposed to toxic substances entering body through ingestion shall wash face and hands thoroughly before eating, drinking, smoking, or leaving premises',
    },

    washroomTime: {
      subsection: '1093.15',
      allowance: 'Time allowance for washroom before meal period and shower at end of day',
      forSubstances: [
        'Irritating or toxic dry mineral/organic substances (arsenic, chrome, lead, manganese, mercury, phosphorus, zinc and compounds)',
        'Superphosphates and compounds',
        'Dust-producing toxic dyestuffs and pigments',
        'Dust-producing coal-tar products (pitch, soot)',
        'Radioactive substances',
      ],
    },

    medicalAid: {
      subsection: '1093.16',
      requirement: 'Workers shall report promptly any physical complaints',
    },

    exposureRecords: {
      subsection: '1093.17',
      requirement: 'Maintain accurate record of employee exposure to potentially toxic materials',
      access: 'Open to authorized agents and exposed workers',
    },
  },

  // ===========================================
  // SECTION 1094: HOT AND CORROSIVE SUBSTANCES
  // ===========================================
  hotAndCorrosive: {
    section: '1094',

    protectionOfStructure: {
      subsection: '1094.01',
      requirement: 'Adequate measures to prevent damage to structural parts and equipment by corrosion',
    },

    handling: {
      subsection: '1094.02',
      bulkHandling: 'Gravity system or pressure pump system extending to point of use (eliminate small containers)',
      emptyingReceptacles: 'Use pumps, tipping appliances, or suitable apparatus',
      portableReceptacles: 'Transport without escape of fumes or mists, preferably by mechanical means',
      closure: 'Receptacles kept securely closed except during extraction',
    },

    spillageAcidsAlkalies: {
      subsection: '1094.03',
      floors: 'Keep as dry as possible',
      spillAvoidance: 'Spilled liquid shall be guarded until removed',
      acidSpill: {
        prohibition: 'Shall NOT be absorbed by sawdust, waste cloth, or other organic materials',
        correct: 'Flushed with water or neutralized with chalk or lime',
      },
    },

    dilutingAcids: {
      subsection: '1094.04',
      rule: 'ACID INTO WATER with constant stirring',
      prohibition: 'NEVER pour water into acid',
    },

    physicalContact: {
      subsection: '1094.05',
      ppe: 'Protective clothing and equipment per Rule 1080',
      facilities: 'Clean running water, quick-operating eye fountains, and shower baths readily accessible',
    },
  },

  // ===========================================
  // SECTION 1095: STORAGE
  // ===========================================
  storage: {
    section: '1095',

    vatsAndTanks: {
      subsection: '1095.01',

      openTanks: {
        whenTopLessThan1m: 'Raise top to at least 1 m (3.3 ft.) OR guard with enclosures/railings',
        whenTopLessThan15cm: 'Provide standard toeboards',
        adjoiningTanks: 'Space shall be fenced',
        drainage: 'Pipes or drains of sufficient capacity without spilling or backing up',
      },

      aboveGroundTanks: {
        containment: 'Surrounded by pits, catch basins, or depressions to hold entire contents',
        overflow: 'Overflow pipes leading to tanks or safe places outside building',
      },

      walkways: {
        prohibition: 'Walkways shall not cross over open vats/tanks with hazardous liquids',
        serviceWalkways: {
          width: 'Not less than 50 cm (20 in.)',
          railings: 'Standard railings and toeboards on both sides',
          condition: 'Kept clean and dry at all times',
        },
      },
    },

    storageTanks: {
      subsection: '1095.02',

      nonFlammableHazardous: {
        requirements: [
          'Located above ground or floor level',
          'Supported so leakage is noticeable',
          'Surrounded by containment for entire contents',
          'Protective paint against corrosion',
          'Stairways or permanent ladders with platforms for safe access',
        ],
        prohibition: 'Not placed above passageways',
      },

      sunkenTanks: {
        pits: 'Concrete or masonry with passage space between walls and tanks',
        mounting: '38 to 45 cm (15 to 18 in.) above pit bottom',
        covers: 'With fixed ladders for safe access',
        valves: 'Operable without entering pit, with locking devices from outlet',
      },

      corrosiveTanks: {
        ventPipe: 'Permanent open wet pipe min 5 cm (2 in.) diameter at highest point',
        drain: 'At lowest point, discharging to safe place',
        filling: 'Connections at top',
        discharge: 'Pipes 15 cm (6 in.) above bottom',
      },
    },

    acidDrums: {
      subsection: '1095.03',
      storage: 'Cool places with bung up',
      pressure: 'Open carefully after moving or weekly if stored, to relieve internal pressure',
    },

    carboysForAcids: {
      subsection: '1095.04',
      encasement: 'Singly in baskets or boxes cushioned with noncombustible packing',
      storageRoom: {
        floors: 'Concrete with anti-acid protection or brick, properly drained',
        conditions: 'Dry, protected from dampness, extreme heat, or sudden temperature change',
      },
      prohibition: 'Shall not be piled one on top of another',
      placement: 'Suitable storage racks or wooden strips on floor',
      handling: 'Two-wheeled carboy trucks for transport',
      emptying: 'Adequate equipment provided',
      emptyCarboys: {
        storage: 'Stored apart from filled carboys',
        washing: 'Thoroughly washed upside down with water stream and drained before storage',
      },
      inspection: 'Examine carboys and containers before filling',
    },
  },

  // ===========================================
  // SECTION 1096: USE OF LEAD AND ITS COMPOUNDS
  // ===========================================
  leadCompounds: {
    section: '1096',

    definition: {
      subsection: '1096.01',
      leadCompounds: 'Any organic or inorganic derivatives of lead',
    },

    controlMeasures: {
      subsection: '1096.02',
      substitution: 'Use less harmful substitutes (e.g., zinc oxide or titanium oxide instead of white lead in paint)',
      enclosure: 'Processes enclosed with mechanical handling methods',
    },

    storageAndHandling: {
      subsection: '1096.03',
      storage: 'Keep lead materials in special storage rooms outside workrooms',
      location: 'Lead handling areas confined to small area to concentrate control measures',
    },

    localExhaust: {
      subsection: '1096.04',
      requirement: 'Properly designed exhaust systems to maintain TLV of lead in atmosphere',
      prohibition: 'Contaminants removed shall not re-enter workrooms or pollute surroundings',
    },

    ppe: {
      subsection: '1096.05',
      equipment: ['Overalls', 'Head covering', 'Goggles', 'Gloves', 'Aprons', 'Respirators'],
      provision: 'Issued FREE of charge by employer',
      responsibility: 'Employer ensures proper use and maintenance',
    },

    smokingOrEating: {
      subsection: '1096.06',
      prohibition: 'Smoking, chewing, eating, and keeping of food in lead workrooms NOT allowed',
    },

    storageLockers: {
      subsection: '1096.07',
      requirement: 'Suitable storage lockers for street and work clothes for each worker',
      facilities: 'Adequate washing facilities provided',
    },

    physicalExamination: {
      subsection: '1096.08',
      frequency: {
        normal: 'At least every 6 months',
        elevated: 'At least every 3 months if contamination above TLV',
      },
      includes: 'Physical and laboratory examination',
      records: 'Open to authorized agents and exposed workers',
    },
  },

  // ===========================================
  // HAZARD CATEGORIES FOR LABELLING
  // ===========================================
  hazardCategories: [
    'Explosive',
    'Flammable',
    'Oxidizing',
    'Toxic',
    'Corrosive',
    'Radioactive',
  ],

  // ===========================================
  // QUICK REFERENCE
  // ===========================================
  quickReference: {
    labeling: {
      required: 'All containers with hazardous substances',
      shape: 'Rectangular',
      text: 'Black on white background',
      largeContainers: 'Min 2.54 cm (1 in.) letters for >18.92 L',
    },
    testing: 'Atmosphere tested at least annually',
    cleaning: {
      flammableDust: 'Daily from floors, weekly from fixtures',
      toxicAreas: 'Daily outside working hours',
    },
    washroom: 'Time allowance for toxic substance workers',
    dilutingAcid: 'ACID into WATER (never water into acid)',
    spilledAcid: 'Flush with water or neutralize with chalk/lime (NOT organic materials)',
    openTanks: 'Top at least 1 m (3.3 ft.) or guarded',
    lead: {
      medicalExam: 'Every 6 months (3 months if above TLV)',
      substitute: 'Zinc oxide or titanium oxide for white lead',
    },
  },
};

// Helper functions
export function getHazardCategories(): string[] {
  return RULE_1090.hazardCategories;
}

export function getLabelRequirements(): string[] {
  return RULE_1090.generalRules.markingOfContainers.labelRequirements.mustContain;
}

export function getControlMethods(): string[] {
  return RULE_1090.generalRules.controlOfProcesses.methods;
}

export function getDefinition(term: string): string | null {
  const defs = RULE_1090.definitions as Record<string, any>;
  const key = term.toLowerCase().replace(/\s+/g, '');

  for (const [k, v] of Object.entries(defs)) {
    if (k.toLowerCase() === key || v.term?.toLowerCase() === term.toLowerCase()) {
      return v.definition || `On inanimate: ${v.onInanimateSurface}; On living tissue: ${v.onLivingTissue}`;
    }
  }
  return null;
}

export function getAcidHandlingRules(): object {
  return {
    diluting: RULE_1090.hotAndCorrosive.dilutingAcids,
    spillage: RULE_1090.hotAndCorrosive.spillageAcidsAlkalies,
    drums: RULE_1090.storage.acidDrums,
    carboys: RULE_1090.storage.carboysForAcids,
  };
}

export function getLeadExposureRequirements(): object {
  return RULE_1090.leadCompounds;
}

export function getStorageRequirements(type: string): object | string {
  const storage = RULE_1090.storage;

  switch (type.toLowerCase()) {
    case 'vat':
    case 'tank':
    case 'open tank':
      return storage.vatsAndTanks;
    case 'acid drum':
    case 'drum':
      return storage.acidDrums;
    case 'carboy':
      return storage.carboysForAcids;
    default:
      return storage.storageTanks;
  }
}

export function getRule1090Summary(): string {
  return `
Rule 1090 - Hazardous Materials Key Points:

CONTROL HIERARCHY:
1. Substitution (harmless for hazardous)
2. Separate rooms/air-tight enclosure
3. Local exhaust ventilation at source
4. General ventilation
5. PPE (supplementary)

LABELING REQUIREMENTS:
- All containers must be labeled
- Rectangular shape, black on white
- Must include: Symbol, name, risks, precautions, first-aid
- Categories: Explosive, Flammable, Oxidizing, Toxic, Corrosive, Radioactive
- Large containers (>18.92L): Min 2.54 cm letters

ATMOSPHERE TESTING: At least annually

CLEANING:
- Flammable dust: Daily (floors), Weekly (fixtures)
- Toxic areas: Daily, outside working hours
- Method: Vacuum, wet brushing, or sweeping

ACID HANDLING:
- Diluting: ACID into WATER (never reverse)
- Spills: Flush with water or neutralize with chalk/lime
- NEVER use sawdust or organic materials on acid spills

STORAGE:
- Open tanks: Top min 1 m high OR guarded
- Above-ground tanks: Containment for entire contents
- Acid drums: Cool, bung up, relieve pressure weekly
- Carboys: Not stacked, cushioned in baskets/boxes

LEAD EXPOSURE:
- Medical exam: Every 6 months (3 months if above TLV)
- Substitute: Zinc/titanium oxide for white lead
- PPE: Free of charge
- No eating/smoking in lead areas

PROHIBITED IN WORKROOM:
- Food, drink, tobacco introduction/consumption
  `.trim();
}
